-- Anomaly detection re-uses the budget_alerts table but adds a new alert type.
--
-- Two schema changes are needed:
--   1. budget_id must allow NULL. An ANOMALY alert flags an unusual charge in a
--      category and is NOT tied to a budget (the user may have no budget for it).
--   2. the alert_type CHECK constraint must accept 'ANOMALY' in addition to the
--      existing values, otherwise inserts would be rejected by the database.

-- 1. Allow anomaly alerts to exist without a budget.
ALTER TABLE budget_alerts ALTER COLUMN budget_id DROP NOT NULL;

-- 2. Replace the CHECK constraint so 'ANOMALY' is a permitted value.
-- The constraint name is auto-generated by Postgres for the inline CHECK in V3,
-- so we drop by the conventional name and re-add an explicitly named one.
ALTER TABLE budget_alerts DROP CONSTRAINT IF EXISTS budget_alerts_alert_type_check;
ALTER TABLE budget_alerts
    ADD CONSTRAINT budget_alerts_alert_type_check
    CHECK (alert_type IN ('WARNING', 'EXCEEDED', 'ANOMALY'));
